sudo: false # use container-based environment on Travis
language: php
php:
  - 5.6
  - hhvm
  - '7'

notifications:
  email:
    recipients:
      - alex@flancer64.com
    on_success: change # [always|never|change], default: change
    on_failure: change # [always|never|change], default: change