sudo: false # use container-based environment on Travis
language: php
php:
  - 5.6
  - hhvm
  - '7'

before_install:
  - composer self-update  # update composer
  - composer install  # install project using PHP Composer

notifications:
  email:
    recipients:
      - alex@flancer64.com
    on_success: change # [always|never|change], default: change
    on_failure: change # [always|never|change], default: change